import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ReactNode, Suspense } from "react";
import { Footer, Header, MobileNav } from "@/components";

import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap", 
});

export const metadata: Metadata = {
  title: {
    default: "Máy Thổi Oxy Đài Loan - Thành Đạt Corp",
    template: "%s | Thành Đạt Corp",
  },
  keywords: ["maythoioxydailoan", "Máy thổi Oxy Đài Loan", "Siêu Tiết Kiệm Điện", "Đầu thổi khí Đài Loan RL"],
  icons: {
    icon: "/logo.png",
  },
  description: "Generated by thuandiep-corp",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body suppressHydrationWarning={true} className={`${roboto.className} antialiased flex flex-col items-center`} >
        <Suspense fallback={<></>}>
          <Header />
          <main className="min-h-screen w-full">
            {children}
          </main>
          <Footer />
          <MobileNav />
        </Suspense>
      </body>
    </html>
  );
}
