import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { Footer, Header, MobileNav } from "@/components";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Máy Thổi Oxy Đài Loan - Thuandiep Corp",
    template: "%s | Thuandiep Corp",
  },
  keywords: ["maythoioxydailoan", "thanhdat", "thoi khi"],
  icons: {
    icon: "/thuandiep-logo.png",
  },
  description: "Generated by thuandiep-corp",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${roboto.className} antialiased flex flex-col items-center`}
      >
        <Header />
        <main className="min-h-screen px-8 w-full max-w-360 ">
          {children}
        </main>
        <Footer />
        <MobileNav />
      </body>
    </html>
  );
}
